title: Intern Life
email: luis.pena.nunez.developer@gmail.com
description:
  Intern Life is the blog where programmers share their knowledge, learn from others, and advance their careers.
baseurl: "" 
url: "https://www.intern.life"
# twitter:
#   username: 
github:
  username: Intern Life
social:
  name: Intern Life
  links:
    - https://github.com/DevWizza/InternLife
    - https://github.com/LuisAlbertoPenaNunez
    - https://github.com/wideckop

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
